services:
  web:
    container_name: ddat-capability-assessment
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    volumes:
      - .:/home/containeruser
    depends_on:
      - db
      - cache
  cache:
    container_name: redis
    image: "redis:7.0-alpine"
    ports:
      - 6379:6379
  db:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mash
      POSTGRES_PASSWORD: mash
      POSTGRES_DB: capability
  